### ISSUE TITLE
Implement specialized logic for different HTTP error codes

### ISSUE THREAD

**Issue by bmikaili** [DataDog/datadog-kafka-connect-logs#11]
The Logs Intake API returns different error codes for different situations:

`413`: For messages exceeding the 5MB limit
`408`: If the connection times out.

We should check if with some error codes, a simple retry is not the correct way to go and instead there could be logic to handle them better.

**Comment by jszwedko** [comment]
Closing this since we our general approach for 4xx status codes is to retry. This is to handle situations where the upstream returns an incorrect status code due to an bug (e.g. 403 or 413).
