### ISSUE TITLE
Hardcoded URL doesn't allow to send logs to different endpoint like EU

### ISSUE THREAD

**Issue by sergialonsaco** [DataDog/datadog-kafka-connect-logs#22]
**Describe what happened:**
I am using this datadog kafka connector but my datadog system is operating in EU

**Describe what you expected:**
To be able to configure the URL from parameters in case a different URL than the US one is wanted to be used.

**Steps to reproduce the issue:**
Trying to send logs to the EU datadog endpoint

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by olivielpeau** [comment]
Thanks @sergialonsaco for opening this issue, we'll triage your feature request.

If you're willing to open a PR to implement this we'd be happy to review it, otherwise we'll triage this on our end and implement it once it's prioritized, thanks!

**Comment by sergialonsaco** [comment]
Thanks, @olivielpeau! I've created the PR https://github.com/DataDog/datadog-kafka-connect-logs/pull/23 with the changes, I would really appreciate it if you could review it 😄

**Comment by olivielpeau** [comment]
Thanks @sergialonsaco for your contribution! It was merged and released in version `1.1.0` so I'll go ahead and close this issue.
